### ISSUE TITLE
Revert all settings

### ISSUE THREAD

**Issue by kelvinkad** [Aatrick/-NO-ROOT-battery-optimization#1]
How can I revert all changes made by all the .bat files? Specially for settings.bat and extremesettings.bat.
The other ones I can revert it manually just changing ignore to allow, but these 2 I said above changes values which is more difficult to understand how to revert it.

**Comment by Aatrick** [comment]
Most of the values changed are binaries so a 1 accounts as enabled and 0 as disabled. Others are values in hertz, bytes and normal numbers (for example the task scheduler) as some of the settings are better left changed and some are android defaults recommendation, here's the two files for you to roll back the changes.

PS : I didn't testdrive them so feel free to report to me if something goes wrong.
[rollback.zip](https://github.com/user-attachments/files/16881960/rollback.zip)
